name: Push 

on:
  push:
    branches: ["master"]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        run: |
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint
        run: |
          npx eslint . \
          --config .eslintrc.cjs \
          --ext .js,.jsx,.ts,.tsx \
          --format @microsoft/eslint-formatter-sarif \
          --output-file eslint-results.sarif
          
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: canary

      - name: Install dependencies
        run: |
          bun install

      - name: Generate package
        run: bun run build

      - name: Tests
        run: bun test
        
  build-and-deploy:
    needs: [eslint, tests]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: canary

      - name: Install dependencies and run deploy script
        run: |
          bun install
          bun run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist
        
