name: Run Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: canary

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: |
          bun install

      - name: Generate package
        run: bun run build

      - name: Tests
        run: bun test
